### PR TITLE
Sorting the order of imports based on Pylint

### PR DESCRIPTION
**Pull request by MyGodItsFull0fStars**
I sorted some files so that the imported libraries are now in the proper order.

### CODE REVIEW

**Comment by iklobato** [comment]
Hello! We can add a linter on pre-commit, or add a linter on github actions, whats your thoughts about it?

**Comment by MyGodItsFull0fStars** [comment]
Hello, absolutely! A linter on pre-commit just ensures a basic common format.
A project I sometimes contribute to ([CodeCarbon](https://github.com/mlco2/codecarbon)) has pre-commit but also linter on github actions. I'd recommend you take a look at this approach, of course it might first be more effort, but with pre-commit, contributers can easily lint and format the code locally, but you can ensure on Github that everything was properly formatted with actions.

**Comment by MyGodItsFull0fStars** [comment]
Additionally, thank you very much for adding me as a contributer! Happy to be involved 🙌

**Comment by iklobato** [comment]
> Hello, absolutely! A linter on pre-commit just ensures a basic common format. A project I sometimes contribute to ([CodeCarbon](https://github.com/mlco2/codecarbon)) has pre-commit but also linter on github actions. I'd recommend you take a look at this approach, of course it might first be more effort, but with pre-commit, contributers can easily lint and format the code locally, but you can ensure on Github that everything was properly formatted with actions.

Wow, having carbon quantified its absolutely a market trend, and its become hugely important nowaday, I think its an awesome idea! Lets create a discord channel so we can decide together the next steps, nice to have you Christian!

**Comment by MyGodItsFull0fStars** [comment]
Yes, it's a great project! And there is a lot of stuff already done that is just soooo nice for CI.

**Pull request closed without merging**
